from .assembly import router as assembly_router
from .forecast import router as forecast_router
from .consumption import router as consumption_router
from .files import router as static_files_router
from .pkmc import router as pkmc_router
from .pk05 import router as pk05_router
from .sap_manager import router as sap_router
from .requests_builder import router as requests_builder_router
from .requests_checker import router as requests_checker_router
from .requests_closure import router as requests_closure_router