"""initial migration

Revision ID: 6c6e689cf686
Revises: 
Create Date: 2026-02-09 11:33:20.906815

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6c6e689cf686'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assembly_line',
    sa.Column('knr', sa.String(length=255), nullable=False),
    sa.Column('takt', sa.String(length=255), nullable=False),
    sa.Column('model', sa.String(length=255), nullable=False),
    sa.Column('lfdnr_sequence', sa.String(length=255), nullable=False),
    sa.Column('lane', sa.String(length=255), nullable=False),
    sa.Column('spj', sa.Integer(), nullable=False),
    sa.Column('werk', sa.Integer(), nullable=False),
    sa.Column('knr_fx4pd', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('knr')
    )
    op.create_table('forecast',
    sa.Column('partnumber', sa.String(length=255), nullable=False),
    sa.Column('num_reg_circ', sa.String(length=255), nullable=False),
    sa.Column('takt', sa.String(length=255), nullable=False),
    sa.Column('rack', sa.String(length=255), nullable=False),
    sa.Column('lb_balance', sa.Float(), nullable=False),
    sa.Column('total_theoretical_qty', sa.Float(), nullable=False),
    sa.Column('qty_for_restock', sa.Float(), nullable=False),
    sa.Column('qty_per_box', sa.Float(), nullable=False),
    sa.Column('qty_max_box', sa.Float(), nullable=False),
    sa.Column('knr_fx4pd', sa.String(length=255), nullable=False),
    sa.Column('qty_usage', sa.Float(), nullable=False),
    sa.Column('qty_unit', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('partnumber', 'knr_fx4pd')
    )
    op.create_table('fx4pd',
    sa.Column('knr_fx4pd', sa.String(length=255), nullable=False),
    sa.Column('partnumber', sa.String(length=255), nullable=False),
    sa.Column('qty_usage', sa.Float(), nullable=False),
    sa.Column('qty_unit', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('knr_fx4pd', 'partnumber', 'qty_usage', 'qty_unit')
    )
    op.create_table('pk05',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('supply_area', sa.String(length=255), nullable=False),
    sa.Column('deposit', sa.String(length=255), nullable=False),
    sa.Column('responsible', sa.String(length=255), nullable=False),
    sa.Column('discharge_point', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('takt', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pk05_id'), 'pk05', ['id'], unique=False)
    op.create_table('pkmc',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('partnumber', sa.String(length=255), nullable=False),
    sa.Column('supply_area', sa.String(length=255), nullable=False),
    sa.Column('num_reg_circ', sa.String(length=255), nullable=False),
    sa.Column('deposit_type', sa.String(length=255), nullable=False),
    sa.Column('deposit_position', sa.String(length=255), nullable=False),
    sa.Column('container', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('pack_standard', sa.String(length=255), nullable=False),
    sa.Column('qty_per_box', sa.Float(), nullable=False),
    sa.Column('qty_max_box', sa.Float(), nullable=False),
    sa.Column('total_theoretical_qty', sa.Float(), nullable=False),
    sa.Column('qty_for_restock', sa.Float(), nullable=False),
    sa.Column('rack', sa.String(length=255), nullable=False),
    sa.Column('lb_balance', sa.Float(), nullable=False),
    sa.Column('lb_balance_box', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pkmc_id'), 'pkmc', ['id'], unique=False)
    op.create_table('requests_made',
    sa.Column('partnumber', sa.String(length=255), nullable=False),
    sa.Column('num_reg_circ', sa.String(length=255), nullable=False),
    sa.Column('qty_to_request', sa.Float(), nullable=False),
    sa.Column('qty_boxes_to_request', sa.Float(), nullable=False),
    sa.Column('takt', sa.String(length=255), nullable=False),
    sa.Column('rack', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('partnumber')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('requests_made')
    op.drop_index(op.f('ix_pkmc_id'), table_name='pkmc')
    op.drop_table('pkmc')
    op.drop_index(op.f('ix_pk05_id'), table_name='pk05')
    op.drop_table('pk05')
    op.drop_table('fx4pd')
    op.drop_table('forecast')
    op.drop_table('assembly_line')
    # ### end Alembic commands ###
